//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB2EDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string Doctor_Code { get; set; }
        public string Hospital_Code { get; set; }
        public string Supervising_Doctor_Doctor { get; set; }
        public string Doctor_Name { get; set; }
        public Nullable<decimal> Doctor_Contact_Number { get; set; }
        public string Speciality_Level { get; set; }
    }
}
