//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB2EDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string Patient_Code { get; set; }
        public string Hospital_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Surname { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Town_City { get; set; }
        public string Address_Country { get; set; }
        public string Address_Postal_Zip_Code { get; set; }
        public Nullable<decimal> Patient_ID_Number { get; set; }
        public Nullable<decimal> Patient_Date_Of_Birth { get; set; }
        public string Patient_Occupation { get; set; }
        public Nullable<decimal> Patient_Contact_Number { get; set; }
        public string Patient_Gender { get; set; }
        public string Patient_Status { get; set; }
    }
}
