//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB2EDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public string Hospital_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Ward_Name { get; set; }
    }
}
